# Generated by Django 5.0.1 on 2024-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nif', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=50)),
            ],
        ),
    ]
